### PR TITLE
Exposed options, Custom CDN support, SVG support, Recent emojis category and setFocus

### PR DESCRIPTION
**Pull request by klaslundberg**
Some useful additions, nothing that breaks existing usage.

Most importantly it may use settings already configured in emojione when it's already loaded before.

Recent emojis is a nice addition.

### CODE REVIEW

**Comment by mervick** [comment]
Hi,
Thanks for your contribution

**Comment by klaslundberg** [comment]
I noticed a bug in the recent list, regarding events, which causes multiple emojis to be inserted in som cases. Working on a fix, will probably be ready today.

**Comment by klaslundberg** [comment]
I'm not quite getting my head around the events right now, but will get back to you in next week. Let me know if you have any tips regarding the events in updateRecent.

**Comment by mervick** [comment]
I think when typing the emoji that is present in recent list it must be placed in the beginning of the list
in `setRecent.js` something like this
```js
    var index = emojis.indexOf(emoji);
    if (index !== -1) {
        emojis.splice(index, 1);
    }
    emojis.unshift(emoji);
```
Also, I think it need to create option (for example) `recentEmojis` with default is `true` for ability to turn off recent emojis

**Comment by mervick** [comment]
Also I noticed: function `loadEmojione` should not be called more than once

**Comment by glui2001** [comment]
thx for the prompt update guys!!!!!!!

**Comment by klaslundberg** [comment]
About the loadEmojis: I changed how it was called to get it to read custom options. Therefore I added a check so that it doesn't load if it's already loading, to avoid multiple script load requests. It would off course be better if it only got called once, but I couldn't get that to play nicely with the exposed options. So this could probably be optimized.

**Comment by klaslundberg** [comment]
Found the problem with the events. It was the on/off that was using @ when it shouldn't. That caused the off to not unregister the handler, when updating the emojis. I will make a new pull request with this fix.

**Pull request merged**
