### PR TITLE
Add standalone mode for version 3

### PR DESCRIPTION
**Pull request by MerlinBB**
Managed to do this in a more simple manner this time... Keeping the editor element but simply replacing the html every time a choice is made. Seems cleaner, but happy to make changes if you're not happy.

Couple of things...

- I haven't really managed to add much styling as I'm getting a compile error with the scss 
`File not found or cannot be read: ./images/sprite.png on line 37 of scss/_image.scss, in inline-images-flash from line 524 of scss/emojionearea.scss` any ideas?
- I noticed the `saveEmojisAs` option is currently undocumented (I think `shortnames` needs replacing)

### CODE REVIEW

**Comment by mervick** [comment]
Hi. You are fast. 
`saveEmojisAs` used for saving unlike `shortnames` that allow to parse `shortnames` from source.

> File not found or cannot be read: ./images/sprite.png on line 37 of scss/_image.scss, in inline-images-flash from line 524 of scss/emojionearea.scss

Maybe different version of `compass` or `sass`, just rename dir `img` to `images` for compiling `sass` files

**Comment by mervick** [comment]
Let me know when you finish

**Comment by MerlinBB** [comment]
Don't think I'll have time tonight -  but will do this first thing tomorrow :)

**Comment by MerlinBB** [comment]
Ok think this may be good now - let me know what you think.

image

**Comment by mervick** [comment]
It's perfect. Except one.
Now on standalone mode the picker by default must be shown 
at left-top or at left-bottom. But this styles missing
In anyway it's a good work.
Thanks)

**Comment by MerlinBB** [comment]
Awesome, thanks!

**Pull request merged**
