### PR TITLE
Standalone mode

### PR DESCRIPTION
**Pull request by MerlinBB**
Hey not sure if you're interested in merging this but I needed it personally so thought I would share...

Pull request adds a standalone mode which can be used for emoji reactions or any use case where you may only want to use a single emoji and not have a textarea.

Let me know what you think 😄

### CODE REVIEW

**Comment by MerlinBB** [comment]
Hey there,

Any thoughts on wether or not you might integrate this? I love the changes you've made on v3 and would like to use them in my project... Cheers!

**Comment by mervick** [comment]
Hi, @MerlinBB, thanks for your improvements, it's realy cool.
Sorry, still can not find the time.
I wanted to make some more changes.
But in any way hands did not reach.

Now I'll create a new branch with your changes.
Thanks again.

**Comment by mervick** [comment]
This branch has conflicts, could you create new pull request to `version2` branch for storing you in contributors.
Thanks

**Comment by MerlinBB** [comment]
No problem, new pull request raised here: https://github.com/mervick/emojionearea/pull/26

**Comment by MerlinBB** [comment]
Arrgh, quite a few merge conflict in there 💣 

Do you think it's best to try and merge into version 2 or should we just try and implement it directly in version 3?

**Comment by mervick** [comment]
Thank you. 
I think it is best to implement it in both versions. 
If you can do it, I will appreciate it.

**Comment by mervick** [comment]
Was published in release `v2.1.4`

**Comment by MerlinBB** [comment]
Awesome, thanks!

Shall I have a go a integrating this with v3 then?

**Comment by mervick** [comment]
If you want

**Pull request closed without merging**
