### PR TITLE
Fixed some icon short_names : :keycap_ten: to :ten:, :cross_heavy: to :cross:, :contruction_site: to :construction_site:

### PR DESCRIPTION
**Pull request by sheyooo**
It seems there has been some changes to the Emojione library because `:keycap_ten:` works in your demo, but changing it fixed some missing icons in the sprites. It all looks good now..

### CODE REVIEW

**Comment by mervick** [comment]
Which version of emojione you are using?
For v1.5.0 it worked before you remove toUpperCase() method, now it seems to be broken.

**Comment by sheyooo** [comment]
I use version 2.1.1 https://github.com/Ranks/emojione/releases

**Comment by mervick** [comment]
If you want to add support for emojione >v1.5.0, is necessary to support older versions too.

**Comment by sheyooo** [comment]
alright will work on it

**Comment by sheyooo** [comment]
@mervick review and see tested it works fine

**Comment by mervick** [comment]
Just finished work on new emojione support, has released v2.0.0. 
For now emojione v1.5.0-v2.1.1 has support.

**Pull request closed without merging**
