### PR TITLE
Trivial usability tweak to CSS

### PR DESCRIPTION
**Pull request by carpii**
Emoji icons currently have a 1px margin, which means when you hover or click one, you can easily end up not selecting any 

Remove the margin and compensate by increasing padding, so you will always click and hover over one

### CODE REVIEW

**Comment by mervick** [comment]
This margin added special for make distance between icons

**Comment by carpii** [comment]
Could you explain please? 

If you hover or click the 1px margin it ends up not doing anything. By increasing padding it seems to work identically, except now all clicks and hovers work

**Comment by mervick** [comment]
Between clickable UI must be always margin, It's a bad tradition not to leave distances between elements

**Comment by mervick** [comment]
I think in that place must be a margin

**Comment by carpii** [comment]
Ok, I really don't agree but you are the owner :)

People trying to over or click on an emoji and then accidentally clicking on a margin, just makes the control seem erratic

**Comment by mervick** [comment]
I don't think it's can be an issue, between many UI elements there are margin,
especially between buttons, because you can accidentally press the wrong button

**Comment by carpii** [comment]
Ok, will delete my contributions yet again..

**Pull request closed without merging**
